version: '3.9'

services:
  ntpd:
    image: dalbodeule/ntpd:latest
    container_name: ntpd
    restart: unless-stopped
    ports:
      - "123:123/udp"
    volumes:
      - ./ntpd.conf:/etc/ntpd.conf:ro
      - ./ntpd.drift:/var/db/ntpd.drift:rw
    cap_add:
      - SYS_TIME
    environment:
      - TZ=Asia/Seoul