version: '3.9'

services:
  ntpd:
    image: nicholasdille/openntpd:latest
    container_name: ntpd
    restart: unless-stopped
    ports:
      - "123:123/udp"
    volumes:
      - ./ntpd.conf:/etc/ntpd.conf:ro
    cap_add:
      - SYS_TIME
    environment:
      - TZ=Asia/Seoul